export const params = [
  {
    title: 'Title1',
    rows: ['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
  },
  {
    title: 'Title2',
    rows: ['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
  },
  {
    title: 'Title3',
    rows: ['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
  },
  {
    title: 'Title4',
    rows: ['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
  },
  {
    title: 'Title5',
    rows: ['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8'],
  },
];

export const table1 = [
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
];

export const table2 = [
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
  {
    code: 'KOK78',
    product: 'Рама',
    description: 'Текст5',
    price: '73',
  },
  {
    code: 'XFI21',
    product: 'Стул',
    description: 'Текст6',
    price: '36',
  },
  {
    code: 'XL233',
    product: 'Стол',
    description: 'Текст7',
    price: '72',
  },
  {
    code: 'AKSJD28',
    product: 'Дверь',
    description: 'Текст1',
    price: '123',
  },
  {
    code: 'SDJ99',
    product: 'Окно',
    description: 'Текст2',
    price: '23',
  },
  {
    code: 'LW32',
    product: 'Штора',
    description: 'Текст3',
    price: '421',
  },
  {
    code: 'XLCK42',
    product: 'Стена',
    description: 'Текст4',
    price: '213',
  },
];
